include_recipe "../cookbooks/yum_update/default.rb"
include_recipe "../cookbooks/git/default.rb"
include_recipe "../cookbooks/remi/default.rb"
include_recipe "../cookbooks/nginx/default.rb"
include_recipe "../cookbooks/php/default.rb"
include_recipe "../cookbooks/ndenv/default.rb"
include_recipe "../cookbooks/nodejs/default.rb"
include_recipe "../cookbooks/mysql/default.rb"
